# Generated by Django 5.2.6 on 2025-09-26 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('color', models.CharField(max_length=50)),
                ('daily_rental_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['brand', 'model', 'year'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('driver_license_number', models.CharField(max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='ExtraService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'extra service',
                'verbose_name_plural': 'extra services',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='reserved', max_length=20)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='rentals.car')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='rentals.client')),
                ('extra_services', models.ManyToManyField(blank=True, related_name='rentals', to='rentals.extraservice')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
