# Generated by Django 5.2.6 on 2025-09-26 13:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ekexam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam_date', models.DateField()),
                ('task_image', models.ImageField(upload_to='exam_tasks/')),
                ('is_public', models.BooleanField(default=False)),
                ('participants', models.ManyToManyField(blank=True, related_name='ek_exams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'exam',
                'verbose_name_plural': 'exams',
                'ordering': ['-exam_date', '-created_at'],
            },
        ),
    ]
